apiVersion: v1
kind: Pod
metadata:
  name: postgrespod
  labels:
    name: postgrespod
    app: demovotingapp

spec:
  containers:
    - name: postgressapp
      image: postgres:9.4
      ports:
        - containerPort: 5432