apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: demovotingapp

spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgrespod
    app: demovotingapp