apiVersion: v1
kind: Pod
metadata:
  name: redispod
  labels:
    name: redispod
    app: demovotingapp

spec:
  containers:
    - name: redisapp
      image: redis
      ports:
        - containerPort: 6379