apiVersion: v1
kind: Pod
metadata:
  name: resultpod
  labels:
    name: resultpod
    app: demovotingapp

spec:
  containers:
    - name: resultapp
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
