apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-service
    app: demovotingapp

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 305001
  selector:
    name: resultpod
    app: demovotingapp