apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demovotingapp

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30500
  selector:
    name: votingpod
    app: demovotingapp